language: ruby
rvm:
  - 2.6.5
env:
  - DB_USERNAME=d DB_USERNAME=postgrestest DB_PASSWORD=postgrestest CONSUMER_KEY=d CONSUMER_SECRET=d ACCESS_TOKEN=d ACCESS_TOKEN_SECRET=d
script: 
  - docker-compose up -d
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec